version: '3.8'

services:
  autofill-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CORS_ORIGINS=*
    volumes:
      - ./templates:/app/templates
      - ./outputs:/app/outputs
    restart: unless-stopped

