import random
from datetime import datetime, timedelta

class RandomDataGenerator:
    def __init__(self):
        self.data_pools = {
            # Vessel Names (50+ realistic options based on actual maritime naming conventions)
            'vessel_name': [
                'MT Maersk Challenger', 'MV COSCO Shanghai', 'MT Evergreen Harmony', 'MV CMA CGM Liberty',
                'MT MSC Magnifica', 'MV Hapag-Lloyd Express', 'MT ONE Innovation', 'MV Yang Ming Pioneer',
                'MT OOCL Excellence', 'MV Hyundai Confidence', 'MT K Line Discovery', 'MV MOL Triumph',
                'MT NYK Voyager', 'MV Zim Integrated', 'MT Wan Hai Progress', 'MV Pacific International',
                'MT Atlantic Navigator', 'MV Nordic Breeze', 'MT Mediterranean Star', 'MV Baltic Pioneer',
                'MT Caribbean Explorer', 'MV Indian Ocean Glory', 'MT Red Sea Champion', 'MV Black Sea Spirit',
                'MT Caspian Voyager', 'MV Aegean Princess', 'MT North Sea Titan', 'MV Adriatic Crown',
                'MT Ionian Star', 'MV Tyrrhenian Wave', 'MT Coral Sea Explorer', 'MV Tasman Navigator',
                'MT Bering Strait', 'MV Gulf Stream', 'MT Labrador Current', 'MV Kuroshio Flow',
                'MT Benguela Drift', 'MV Agulhas Current', 'MT California Stream', 'MV Canary Current',
                'MT Brazil Current', 'MV Falkland Flow', 'MT Antarctic Explorer', 'MV Equatorial Star',
                'MT Monsoon Spirit', 'MV Trade Wind', 'MT Ocean Breeze', 'MV Sea Horizon',
                'MT Global Trader', 'MV Maritime Excellence', 'MT Shipping Pioneer', 'MV Cargo Master'
            ],
            
            # IMO Numbers (50+ realistic options following actual IMO numbering patterns)
            'imo_number': [
                '9234567', '9345678', '9456789', '9567890', '9678901', '9789012', '9890123', '9901234',
                '9012345', '9123456', '9234568', '9345679', '9456780', '9567891', '9678902', '9789013',
                '9890124', '9901235', '9012346', '9123457', '9234569', '9345670', '9456781', '9567892',
                '9678903', '9789014', '9890125', '9901236', '9012347', '9123458', '9234570', '9345671',
                '9456782', '9567893', '9678904', '9789015', '9890126', '9901237', '9012348', '9123459',
                '9234571', '9345672', '9456783', '9567894', '9678905', '9789016', '9890127', '9901238',
                '9012349', '9123450', '9234572', '9345673', '9456784', '9567895', '9678906', '9789017'
            ],
            
            # Company Names (50+ professional maritime industry names)
            'company_name': [
                'Maersk Line A/S', 'COSCO SHIPPING Lines', 'Mediterranean Shipping Company', 'CMA CGM Group',
                'Hapag-Lloyd AG', 'Evergreen Marine Corp', 'Ocean Network Express', 'Yang Ming Marine Transport',
                'Orient Overseas Container Line', 'Hyundai Merchant Marine', 'Kawasaki Kisen Kaisha',
                'Mitsui O.S.K. Lines', 'Nippon Yusen Kabushiki Kaisha', 'Zim Integrated Shipping',
                'Wan Hai Lines Ltd', 'Pacific International Lines', 'Seaspan Corporation',
                'Danaos Corporation', 'Capital Product Partners', 'Safe Bulkers Inc',
                'Star Bulk Carriers Corp', 'Golden Ocean Group', 'Frontline Ltd', 'DHT Holdings Inc',
                'International Seaways Inc', 'Scorpio Tankers Inc', 'Teekay Corporation', 'Euronav NV',
                'Nordic American Tankers', 'Gener8 Maritime Inc', 'Tsakos Energy Navigation',
                'StealthGas Inc', 'GasLog Ltd', 'Golar LNG Limited', 'Flex LNG Ltd',
                'Cool Company Ltd', 'Höegh LNG Holdings', 'Exmar NV', 'Dynagas LNG Partners',
                'Global Ship Lease Inc', 'Costamare Inc', 'Navios Maritime Holdings', 'Diana Shipping Inc',
                'Seanergy Maritime Holdings', 'Castor Maritime Inc', 'Eagle Bulk Shipping Inc',
                'Genco Shipping & Trading', 'Pangaea Logistics Solutions', 'Grindrod Shipping Holdings'
            ],
            
            # Personal Names (50+ diverse professional names)
            'name': [
                'James Anderson', 'Maria Rodriguez', 'David Chen', 'Sarah Johnson', 'Michael Brown',
                'Lisa Wang', 'Robert Taylor', 'Jennifer Davis', 'Christopher Wilson', 'Amanda Garcia',
                'Daniel Martinez', 'Jessica Lee', 'Matthew Thompson', 'Ashley White', 'Andrew Clark',
                'Emily Rodriguez', 'Joshua Lewis', 'Stephanie Hall', 'Ryan Young', 'Michelle King',
                'Brandon Wright', 'Nicole Lopez', 'Kevin Hill', 'Rachel Green', 'Tyler Adams',
                'Samantha Baker', 'Justin Nelson', 'Lauren Carter', 'Aaron Mitchell', 'Megan Perez',
                'Nathan Roberts', 'Kayla Turner', 'Jordan Phillips', 'Brittany Campbell', 'Zachary Parker',
                'Danielle Evans', 'Ian Edwards', 'Courtney Collins', 'Sean Stewart', 'Vanessa Sanchez',
                'Trevor Morris', 'Jasmine Rogers', 'Caleb Reed', 'Sierra Cook', 'Garrett Bailey',
                'Alexis Rivera', 'Blake Cooper', 'Destiny Richardson', 'Mason Cox', 'Paige Howard'
            ],
            
            # Professional Designations (30+ maritime and business titles)
            'designation': [
                'Chief Executive Officer', 'Chief Operating Officer', 'Chief Financial Officer',
                'Managing Director', 'General Manager', 'Operations Manager', 'Commercial Manager',
                'Technical Manager', 'Fleet Manager', 'Port Captain', 'Marine Superintendent',
                'Vessel Operations Manager', 'Chartering Manager', 'Bunker Manager', 'Claims Manager',
                'HSQE Manager', 'Crewing Manager', 'Procurement Manager', 'Finance Manager',
                'Business Development Manager', 'Regional Manager', 'Country Manager', 'Branch Manager',
                'Senior Vice President', 'Vice President', 'Assistant Vice President', 'Director',
                'Senior Manager', 'Manager', 'Assistant Manager', 'Senior Executive', 'Executive',
                'Senior Officer', 'Officer', 'Coordinator', 'Specialist', 'Analyst', 'Representative'
            ],
            
            # Port Names (50+ major international ports)
            'port_name': [
                'Port of Shanghai', 'Port of Singapore', 'Port of Ningbo-Zhoushan', 'Port of Shenzhen',
                'Port of Guangzhou', 'Port of Busan', 'Port of Hong Kong', 'Port of Qingdao',
                'Port of Tianjin', 'Port of Rotterdam', 'Port of Dubai', 'Port of Los Angeles',
                'Port of Antwerp', 'Port of Xiamen', 'Port of Kaohsiung', 'Port of Dalian',
                'Port of Hamburg', 'Port of Tanjung Pelepas', 'Port of Long Beach', 'Port of Klang',
                'Port of Laem Chabang', 'Port of Bremen', 'Port of Valencia', 'Port of Colombo',
                'Port of Piraeus', 'Port of Jawaharlal Nehru', 'Port of Felixstowe', 'Port of Savannah',
                'Port of Barcelona', 'Port of Algeciras', 'Port of Jeddah', 'Port of New York',
                'Port of Genoa', 'Port of Le Havre', 'Port of Marsaxlokk', 'Port of Gioia Tauro',
                'Port of Tokyo', 'Port of Yokohama', 'Port of Kobe', 'Port of Nagoya',
                'Port of Melbourne', 'Port of Sydney', 'Port of Fremantle', 'Port of Auckland',
                'Port of Vancouver', 'Port of Montreal', 'Port of Santos', 'Port of Buenos Aires',
                'Port of Durban', 'Port of Cape Town', 'Port of Lagos', 'Port of Alexandria'
            ],
            
            # Countries (50+ major trading nations)
            'country': [
                'China', 'United States', 'Germany', 'Japan', 'United Kingdom', 'France', 'India',
                'Italy', 'Brazil', 'Canada', 'Russia', 'South Korea', 'Spain', 'Australia',
                'Mexico', 'Indonesia', 'Netherlands', 'Saudi Arabia', 'Turkey', 'Taiwan',
                'Belgium', 'Argentina', 'Thailand', 'Ireland', 'Israel', 'Nigeria', 'Austria',
                'Egypt', 'South Africa', 'Philippines', 'Bangladesh', 'Chile', 'Finland',
                'Romania', 'Czech Republic', 'Portugal', 'New Zealand', 'Peru', 'Greece',
                'Iraq', 'Algeria', 'Qatar', 'Kazakhstan', 'Hungary', 'Kuwait', 'Ukraine',
                'Morocco', 'Ecuador', 'Angola', 'Ethiopia', 'Ghana', 'Kenya', 'Tanzania'
            ],
            
            # Quantities (various units for cargo/fuel)
            'quantity': [
                '50,000 MT', '75,000 MT', '100,000 MT', '125,000 MT', '150,000 MT', '200,000 MT',
                '25,000 BBL', '50,000 BBL', '75,000 BBL', '100,000 BBL', '150,000 BBL', '200,000 BBL',
                '1,000 CBM', '2,500 CBM', '5,000 CBM', '7,500 CBM', '10,000 CBM', '15,000 CBM',
                '500 TEU', '1,000 TEU', '1,500 TEU', '2,000 TEU', '3,000 TEU', '5,000 TEU'
            ],
            
            # Financial amounts (various currencies and amounts)
            'amount': [
                '$1,250,000', '$2,500,000', '$5,000,000', '$7,500,000', '$10,000,000', '$15,000,000',
                '€1,000,000', '€2,000,000', '€3,500,000', '€5,000,000', '€7,500,000', '€10,000,000',
                '£750,000', '£1,500,000', '£2,250,000', '£3,000,000', '£4,500,000', '£6,000,000',
                '¥150,000,000', '¥300,000,000', '¥500,000,000', '¥750,000,000', '¥1,000,000,000'
            ],
            
            # Contact Information
            'phone': [
                '+1-555-0123', '+1-555-0456', '+1-555-0789', '+44-20-7123-4567', '+44-20-7890-1234',
                '+65-6123-4567', '+65-6890-1234', '+86-21-1234-5678', '+86-21-8901-2345',
                '+49-40-123-456', '+49-40-789-012', '+33-1-23-45-67-89', '+33-1-98-76-54-32',
                '+81-3-1234-5678', '+81-3-8901-2345', '+91-22-1234-5678', '+91-22-8901-2345'
            ],
            
            'email': [
                'operations@maritime.com', 'commercial@shipping.com', 'chartering@vessel.com',
                'bunkers@fuel.com', 'claims@insurance.com', 'technical@fleet.com',
                'manager@port.com', 'director@logistics.com', 'captain@marine.com',
                'superintendent@vessel.com', 'coordinator@cargo.com', 'analyst@trade.com'
            ],
            
            # Dates (various formats)
            'date': [
                '2024-01-15', '2024-02-20', '2024-03-25', '2024-04-10', '2024-05-17', '2024-06-22',
                '2024-07-08', '2024-08-14', '2024-09-19', '2024-10-03', '2024-11-11', '2024-12-28'
            ],
            
            # Addresses
            'address': [
                '123 Maritime Plaza, Singapore 018956', '456 Shipping Street, Rotterdam 3011 AD',
                '789 Port Avenue, Hamburg 20457', '321 Ocean Drive, Hong Kong', '654 Harbor Road, Dubai',
                '987 Vessel Way, Antwerp 2000', '147 Cargo Lane, Los Angeles, CA 90731',
                '258 Terminal Blvd, Long Beach, CA 90802', '369 Dock Street, Felixstowe IP11 3SY',
                '741 Wharf Road, Southampton SO14 3QN', '852 Pier Avenue, Piraeus 18510',
                '963 Berth Street, Valencia 46024', '159 Quay Road, Le Havre 76600'
            ],
            
            # Vessel specifications
            'dwt': ['50,000 DWT', '75,000 DWT', '100,000 DWT', '150,000 DWT', '200,000 DWT', '300,000 DWT'],
            'loa': ['180m', '220m', '250m', '280m', '320m', '350m'],
            'beam': ['28m', '32m', '36m', '42m', '48m', '58m'],
            'draft': ['12.5m', '14.2m', '16.8m', '18.5m', '20.2m', '22.5m'],
            
            # Cargo specifications
            'grade': ['Premium', 'Regular', 'High Grade', 'Standard', 'Marine Grade', 'Aviation Grade'],
            'specification': ['ASTM D975', 'ISO 8217', 'EN 590', 'ASTM D396', 'ISO 3104', 'ASTM D4052'],
            
            # Document references
            'document_number': ['DOC-2024-001', 'DOC-2024-002', 'DOC-2024-003', 'REF-2024-A001', 'REF-2024-B002'],
            'pop_reference': ['POP-2024-001', 'POP-2024-002', 'POP-2024-003', 'POP-REF-001', 'POP-REF-002'],
            'notary_number': ['NOT-2024-001', 'NOT-2024-002', 'NOTARY-001', 'NOTARY-002'],
            'issue_date': ['2024-01-15', '2024-02-20', '2024-03-25', '2024-04-10', '2024-05-17'],
            
            # Fuel/Chemical Properties
            'dist_ibp': ['145°C', '150°C', '155°C', '160°C', '165°C'],
            'dist_10': ['180°C', '185°C', '190°C', '195°C', '200°C'],
            'dist_50': ['250°C', '255°C', '260°C', '265°C', '270°C'],
            'dist_90': ['320°C', '325°C', '330°C', '335°C', '340°C'],
            'dist_fbp': ['360°C', '365°C', '370°C', '375°C', '380°C'],
            'dist_residue': ['1.5%', '2.0%', '2.5%', '3.0%', '3.5%'],
            'smoke_point': ['18mm', '20mm', '22mm', '25mm', '28mm'],
            'cloud_point': ['-5°C', '-10°C', '-15°C', '-20°C', '-25°C'],
            'cfpp': ['-10°C', '-15°C', '-20°C', '-25°C', '-30°C'],
            'carbon_residue': ['0.05%', '0.10%', '0.15%', '0.20%', '0.25%'],
            'viscosity_40': ['2.5 cSt', '3.0 cSt', '3.5 cSt', '4.0 cSt', '4.5 cSt'],
            'viscosity_100': ['1.8 cSt', '2.0 cSt', '2.2 cSt', '2.5 cSt', '2.8 cSt'],
            'viscosity_index': ['95', '100', '105', '110', '115'],
            'api_gravity': ['35.5°', '38.2°', '40.8°', '42.5°', '45.1°'],
            'specific_gravity': ['0.845', '0.850', '0.855', '0.860', '0.865'],
            'octane_number': ['87', '89', '91', '93', '95'],
            'calorific_value': ['42.5 MJ/kg', '43.0 MJ/kg', '43.5 MJ/kg', '44.0 MJ/kg', '44.5 MJ/kg'],
            'lubricity': ['460 μm', '480 μm', '500 μm', '520 μm', '540 μm'],
            'aromatics': ['15.5%', '18.2%', '20.8%', '22.5%', '25.1%'],
            'olefins': ['2.5%', '3.0%', '3.5%', '4.0%', '4.5%'],
            'oxygenates': ['1.2%', '1.5%', '1.8%', '2.0%', '2.2%'],
            'nitrogen': ['150 ppm', '200 ppm', '250 ppm', '300 ppm', '350 ppm'],
            'nickel': ['2 ppm', '3 ppm', '4 ppm', '5 ppm', '6 ppm'],
            'vanadium': ['50 ppm', '60 ppm', '70 ppm', '80 ppm', '90 ppm'],
            'sodium': ['5 ppm', '8 ppm', '10 ppm', '12 ppm', '15 ppm'],
            'sediment': ['0.05%', '0.08%', '0.10%', '0.12%', '0.15%'],
            
            # Business/Contract Data
            'buyer_company': ['Global Energy Trading Ltd', 'International Fuel Corp', 'Maritime Resources Inc', 'Ocean Trading Co'],
            'seller_company': ['Refinery Solutions Ltd', 'Petroleum Supply Corp', 'Energy Distribution Inc', 'Fuel Trading Co'],
            'buyer_representative': ['John Smith', 'Sarah Johnson', 'Michael Brown', 'Lisa Wang'],
            'seller_representative': ['David Chen', 'Maria Rodriguez', 'Robert Taylor', 'Jennifer Davis'],
            'buyer_email': ['buyer@globalenergy.com', 'procurement@intlfuel.com', 'trading@maritime.com'],
            'seller_email': ['sales@refinery.com', 'commercial@petroleum.com', 'trading@energy.com'],
            'contract_quantity': ['50,000 MT', '75,000 MT', '100,000 MT', '125,000 MT', '150,000 MT'],
            'shipping_terms': ['FOB', 'CIF', 'CFR', 'DDP', 'EXW'],
            'payment_terms': ['LC at sight', '30 days LC', '60 days LC', 'TT in advance', 'CAD'],
            'delivery_terms': ['Ex-ship', 'Ex-wharf', 'Ex-tank', 'DES', 'DEQ'],
            
            # Vessel Data
            'vessel_type': ['Oil Tanker', 'Chemical Tanker', 'Product Tanker', 'Bulk Carrier', 'Container Ship'],
            'flag': ['Panama', 'Liberia', 'Marshall Islands', 'Singapore', 'Malta'],
            'registry_port': ['Panama City', 'Monrovia', 'Majuro', 'Singapore', 'Valletta'],
            'built_year': ['2018', '2019', '2020', '2021', '2022'],
            'classification': ['ABS', 'DNV GL', 'Lloyd\'s Register', 'Bureau Veritas', 'ClassNK']
        }

    def get_random_value(self, placeholder_key):
        """Get a random value for a given placeholder key."""
        normalized_key = self._normalize_key(placeholder_key)
        
        # Check if we have data for this normalized key
        if normalized_key in self.data_pools:
            return random.choice(self.data_pools[normalized_key])
        
        # Generate fallback value
        return self._generate_fallback_value(placeholder_key)

    def _normalize_key(self, key):
        """Normalize placeholder keys to match our data pools."""
        key = key.lower().strip()
        
        # Comprehensive key mappings
        key_mappings = {
            # Vessel information
            'vessel name': 'vessel_name',
            'ship name': 'vessel_name',
            'vessel': 'vessel_name',
            'ship': 'vessel_name',
            'imo': 'imo_number',
            'imo number': 'imo_number',
            'vessel imo': 'imo_number',
            'ship imo': 'imo_number',
            'flag': 'flag',
            'flag state': 'flag',
            'vessel flag': 'flag',
            'built': 'built_year',
            'built year': 'built_year',
            'year built': 'built_year',
            'classification': 'classification',
            'class': 'classification',
            'vessel class': 'classification',
            'registry port': 'registry_port',
            'port of registry': 'registry_port',
            'vessel type': 'vessel_type',
            'ship type': 'vessel_type',
            'type': 'vessel_type',
            
            # Company information
            'company': 'company_name',
            'company name': 'company_name',
            'buyer': 'buyer_company',
            'buyer company': 'buyer_company',
            'seller': 'seller_company',
            'seller company': 'seller_company',
            'charterer': 'company_name',
            'owner': 'company_name',
            'operator': 'company_name',
            
            # Personal information
            'name': 'name',
            'captain': 'name',
            'master': 'name',
            'chief engineer': 'name',
            'chief officer': 'name',
            'representative': 'name',
            'buyer representative': 'buyer_representative',
            'seller representative': 'seller_representative',
            'contact person': 'name',
            'manager': 'name',
            'director': 'name',
            'officer': 'name',
            
            # Contact information
            'phone': 'phone',
            'telephone': 'phone',
            'mobile': 'phone',
            'contact': 'phone',
            'email': 'email',
            'e-mail': 'email',
            'buyer email': 'buyer_email',
            'seller email': 'seller_email',
            
            # Designations and titles
            'position': 'designation',
            'title': 'designation',
            'designation': 'designation',
            'rank': 'designation',
            'role': 'designation',
            
            # Location information
            'port': 'port_name',
            'port name': 'port_name',
            'loading port': 'port_name',
            'discharge port': 'port_name',
            'destination': 'port_name',
            'origin': 'port_name',
            'country': 'country',
            'nation': 'country',
            'state': 'country',
            'address': 'address',
            'location': 'address',
            
            # Cargo and specifications
            'quantity': 'quantity',
            'amount': 'amount',
            'volume': 'quantity',
            'tonnage': 'quantity',
            'cargo': 'quantity',
            'grade': 'grade',
            'quality': 'grade',
            'specification': 'specification',
            'spec': 'specification',
            'standard': 'specification',
            
            # Vessel specifications
            'dwt': 'dwt',
            'deadweight': 'dwt',
            'loa': 'loa',
            'length': 'loa',
            'beam': 'beam',
            'width': 'beam',
            'draft': 'draft',
            'draught': 'draft',
            
            # Dates and times
            'date': 'date',
            'time': 'date',
            'eta': 'date',
            'etd': 'date',
            'arrival': 'date',
            'departure': 'date',
            'laycan': 'date',
            'delivery': 'date',
            'redelivery': 'date',
            
            # Financial terms
            'price': 'amount',
            'rate': 'amount',
            'freight': 'amount',
            'demurrage': 'amount',
            'despatch': 'amount',
            'hire': 'amount',
            'charter rate': 'amount',
            'bunker price': 'amount',
            
            # Commercial terms
            'terms': 'shipping_terms',
            'shipping terms': 'shipping_terms',
            'delivery terms': 'delivery_terms',
            'payment terms': 'payment_terms',
            'contract quantity': 'contract_quantity',
            'contract terms': 'shipping_terms',
            
            # Banking and documentation
            'bank': 'company_name',
            'issuing bank': 'company_name',
            'confirming bank': 'company_name',
            'advising bank': 'company_name',
            'lc number': 'document_number',
            'letter of credit': 'document_number',
            'bl number': 'document_number',
            'bill of lading': 'document_number',
            'invoice number': 'document_number',
            'certificate number': 'document_number',
            'survey report': 'document_number',
            'inspection certificate': 'document_number',
            'quality certificate': 'document_number',
            'quantity certificate': 'document_number',
            'origin certificate': 'document_number',
            'health certificate': 'document_number',
            'phytosanitary certificate': 'document_number',
            'fumigation certificate': 'document_number',
            'insurance certificate': 'document_number',
            'p&i certificate': 'document_number',
            'class certificate': 'document_number',
            'safety certificate': 'document_number',
            'radio certificate': 'document_number',
            'tonnage certificate': 'document_number',
            'load line certificate': 'document_number',
            'cargo manifest': 'document_number',
            'customs declaration': 'document_number',
            'port clearance': 'document_number',
            'health declaration': 'document_number',
            'crew list': 'document_number',
            'passenger list': 'document_number',
            'stores list': 'document_number',
            'bunker delivery note': 'document_number',
            'time sheet': 'document_number',
            'statement of facts': 'document_number',
            'notice of readiness': 'document_number',
            'letter of protest': 'document_number',
            'damage report': 'document_number',
            'incident report': 'document_number',
            'accident report': 'document_number',
            'pollution report': 'document_number',
            'security report': 'document_number',
            'stowaway report': 'document_number',
            'medical report': 'document_number',
            'weather report': 'document_number',
            'noon report': 'document_number',
            'departure report': 'document_number',
            'arrival report': 'document_number',
            'port report': 'document_number',
            'bunker report': 'document_number',
            'cargo report': 'document_number',
            'loading report': 'document_number',
            'discharge report': 'document_number',
            'tank cleaning report': 'document_number',
            'gas free certificate': 'document_number',
            'hot work permit': 'document_number',
            'cold work permit': 'document_number',
            'entry permit': 'document_number',
            'work permit': 'document_number',
            'fire watch': 'document_number',
            'safety meeting': 'document_number',
            'drill report': 'document_number',
            'training record': 'document_number',
            'competency certificate': 'document_number',
            'medical certificate': 'document_number',
            'vaccination certificate': 'document_number',
            'visa': 'document_number',
            'passport': 'document_number',
            'seaman book': 'document_number',
            'discharge book': 'document_number',
            'service record': 'document_number',
            'employment contract': 'document_number',
            'collective agreement': 'document_number',
            'wage agreement': 'document_number',
            'overtime record': 'document_number',
            'leave record': 'document_number',
            'sick leave': 'document_number',
            'shore leave': 'document_number',
            'repatriation': 'document_number',
            'crew change': 'document_number',
            'sign on': 'document_number',
            'sign off': 'document_number',
            'joining letter': 'document_number',
            'relieving letter': 'document_number',
            'recommendation letter': 'document_number',
            'reference letter': 'document_number',
            'experience letter': 'document_number',
            'service certificate': 'document_number',
            'conduct certificate': 'document_number',
            'character certificate': 'document_number',
            'no objection certificate': 'document_number',
            'clearance certificate': 'document_number',
            'completion certificate': 'document_number',
            'attendance certificate': 'document_number',
            'participation certificate': 'document_number',
            'achievement certificate': 'document_number',
            'award certificate': 'document_number',
            'recognition certificate': 'document_number',
            'appreciation certificate': 'document_number',
            'commendation letter': 'document_number',
            'appreciation letter': 'document_number',
            'thank you letter': 'document_number',
            'congratulation letter': 'document_number',
            'invitation letter': 'document_number',
            'notification letter': 'document_number',
            'information letter': 'document_number',
            'instruction letter': 'document_number',
            'directive letter': 'document_number',
            'circular letter': 'document_number',
            'memorandum': 'document_number',
            'notice': 'document_number',
            'announcement': 'document_number',
            'bulletin': 'document_number',
            'newsletter': 'document_number',
            'magazine': 'document_number',
            'journal': 'document_number',
            'publication': 'document_number',
            'brochure': 'document_number',
            'pamphlet': 'document_number',
            'leaflet': 'document_number',
            'flyer': 'document_number',
            'poster': 'document_number',
            'banner': 'document_number',
            'signage': 'document_number',
            'label': 'document_number',
            'tag': 'document_number',
            'sticker': 'document_number',
            'stamp': 'document_number',
            'seal': 'document_number',
            'signature': 'document_number',
            'initial': 'document_number',
            'endorsement': 'document_number',
            'approval': 'document_number',
            'authorization': 'document_number',
            'permission': 'document_number',
            'consent': 'document_number',
            'agreement': 'document_number',
            'contract': 'document_number',
            'charter party': 'document_number',
            'fixture note': 'document_number',
            'recap': 'document_number',
            'confirmation': 'document_number',
            'acceptance': 'document_number',
            'rejection': 'document_number',
            'cancellation': 'document_number',
            'termination': 'document_number',
            'amendment': 'document_number',
            'addendum': 'document_number',
            'supplement': 'document_number',
            'appendix': 'document_number',
            'attachment': 'document_number',
            'enclosure': 'document_number',
            'exhibit': 'document_number',
            'schedule': 'document_number',
            'list': 'document_number',
            'inventory': 'document_number',
            'catalog': 'document_number',
            'directory': 'document_number',
            'index': 'document_number',
            'register': 'document_number',
            'record': 'document_number',
            'log': 'document_number',
            'logbook': 'document_number',
            'diary': 'document_number',
            'journal entry': 'document_number',
            'minute': 'document_number',
            'meeting minute': 'document_number',
            'conference minute': 'document_number',
            'discussion minute': 'document_number',
            'decision minute': 'document_number',
            'resolution': 'document_number',
            'motion': 'document_number',
            'proposal': 'document_number',
            'suggestion': 'document_number',
            'recommendation': 'document_number',
            'advice': 'document_number',
            'guidance': 'document_number',
            'instruction': 'document_number',
            'direction': 'document_number',
            'order': 'document_number',
            'command': 'document_number',
            'request': 'document_number',
            'inquiry': 'document_number',
            'query': 'document_number',
            'question': 'document_number',
            'answer': 'document_number',
            'response': 'document_number',
            'reply': 'document_number',
            'feedback': 'document_number',
            'comment': 'document_number',
            'remark': 'document_number',
            'observation': 'document_number',
            'note': 'document_number',
            'memo': 'document_number',
            'reminder': 'document_number',
            'alert': 'document_number',
            'warning': 'document_number',
            'caution': 'document_number',
            'advisory': 'document_number',
            'bulletin board': 'document_number',
            'message board': 'document_number',
            'notice board': 'document_number',
            'information board': 'document_number',
            'display board': 'document_number',
            'announcement board': 'document_number',
            'communication board': 'document_number',
            'coordination board': 'document_number',
            'planning board': 'document_number',
            'scheduling board': 'document_number',
            'tracking board': 'document_number',
            'monitoring board': 'document_number',
            'control board': 'document_number',
            'management board': 'document_number',
            'executive board': 'document_number',
            'advisory board': 'document_number',
            'review board': 'document_number',
            'evaluation board': 'document_number',
            'assessment board': 'document_number',
            'examination board': 'document_number',
            'inspection board': 'document_number',
            'audit board': 'document_number',
            'investigation board': 'document_number',
            'inquiry board': 'document_number',
            'tribunal': 'document_number',
            'court': 'document_number',
            'panel': 'document_number',
            'committee': 'document_number',
            'commission': 'document_number',
            'council': 'document_number',
            'assembly': 'document_number',
            'congress': 'document_number',
            'parliament': 'document_number',
            'senate': 'document_number',
            'house': 'document_number',
            'chamber': 'document_number',
            'legislature': 'document_number',
            'government': 'document_number',
            'administration': 'document_number',
            'authority': 'document_number',
            'agency': 'document_number',
            'department': 'document_number',
            'ministry': 'document_number',
            'bureau': 'document_number',
            'office': 'document_number',
            'division': 'document_number',
            'section': 'document_number',
            'unit': 'document_number',
            'team': 'document_number',
            'group': 'document_number',
            'crew': 'document_number',
            'staff': 'document_number',
            'personnel': 'document_number',
            'employee': 'document_number',
            'worker': 'document_number',
            'operator': 'document_number',
            'technician': 'document_number',
            'engineer': 'document_number',
            'specialist': 'document_number',
            'expert': 'document_number',
            'consultant': 'document_number',
            'advisor': 'document_number',
            'counselor': 'document_number',
            'mentor': 'document_number',
            'trainer': 'document_number',
            'instructor': 'document_number',
            'teacher': 'document_number',
            'professor': 'document_number',
            'lecturer': 'document_number',
            'speaker': 'document_number',
            'presenter': 'document_number',
            'facilitator': 'document_number',
            'moderator': 'document_number',
            'chairperson': 'document_number',
            'chairman': 'document_number',
            'chairwoman': 'document_number',
            'president': 'document_number',
            'vice president': 'document_number',
            'secretary': 'document_number',
            'treasurer': 'document_number',
            'auditor': 'document_number',
            'accountant': 'document_number',
            'bookkeeper': 'document_number',
            'clerk': 'document_number',
            'assistant': 'document_number',
            'aide': 'document_number',
            'helper': 'document_number',
            'supporter': 'document_number',
            'volunteer': 'document_number',
            'intern': 'document_number',
            'trainee': 'document_number',
            'apprentice': 'document_number',
            'student': 'document_number',
            'pupil': 'document_number',
            'learner': 'document_number',
            'participant': 'document_number',
            'attendee': 'document_number',
            'delegate': 'document_number',
            'representative': 'document_number',
            'agent': 'document_number',
            'broker': 'document_number',
            'dealer': 'document_number',
            'trader': 'document_number',
            'merchant': 'document_number',
            'vendor': 'document_number',
            'supplier': 'document_number',
            'provider': 'document_number',
            'contractor': 'document_number',
            'subcontractor': 'document_number',
            'partner': 'document_number',
            'associate': 'document_number',
            'affiliate': 'document_number',
            'subsidiary': 'document_number',
            'branch': 'document_number',
            'division': 'document_number',
            'department': 'document_number',
            'section': 'document_number',
            'unit': 'document_number',
            'team': 'document_number',
            'group': 'document_number',
            'organization': 'document_number',
            'institution': 'document_number',
            'establishment': 'document_number',
            'enterprise': 'document_number',
            'business': 'document_number',
            'company': 'document_number',
            'corporation': 'document_number',
            'firm': 'document_number',
            'agency': 'document_number',
            'bureau': 'document_number',
            'office': 'document_number',
            'center': 'document_number',
            'facility': 'document_number',
            'plant': 'document_number',
            'factory': 'document_number',
            'mill': 'document_number',
            'workshop': 'document_number',
            'laboratory': 'document_number',
            'research center': 'document_number',
            'development center': 'document_number',
            'training center': 'document_number',
            'education center': 'document_number',
            'learning center': 'document_number',
            'study center': 'document_number',
            'information center': 'document_number',
            'data center': 'document_number',
            'processing center': 'document_number',
            'service center': 'document_number',
            'support center': 'document_number',
            'help center': 'document_number',
            'assistance center': 'document_number',
            'guidance center': 'document_number',
            'counseling center': 'document_number',
            'advisory center': 'document_number',
            'consultation center': 'document_number',
            'coordination center': 'document_number',
            'communication center': 'document_number',
            'control center': 'document_number',
            'command center': 'document_number',
            'operation center': 'document_number',
            'management center': 'document_number',
            'administration center': 'document_number',
            'executive center': 'document_number',
            'headquarters': 'document_number',
            'head office': 'document_number',
            'main office': 'document_number',
            'central office': 'document_number',
            'regional office': 'document_number',
            'local office': 'document_number',
            'branch office': 'document_number',
            'field office': 'document_number',
            'satellite office': 'document_number',
            'remote office': 'document_number',
            'virtual office': 'document_number',
            'mobile office': 'document_number',
            'temporary office': 'document_number',
            'project office': 'document_number',
            'site office': 'document_number',
            'construction office': 'document_number',
            'sales office': 'document_number',
            'marketing office': 'document_number',
            'customer service office': 'document_number',
            'technical office': 'document_number',
            'engineering office': 'document_number',
            'design office': 'document_number',
            'planning office': 'document_number',
            'procurement office': 'document_number',
            'purchasing office': 'document_number',
            'supply office': 'document_number',
            'logistics office': 'document_number',
            'shipping office': 'document_number',
            'receiving office': 'document_number',
            'warehouse office': 'document_number',
            'storage office': 'document_number',
            'distribution office': 'document_number',
            'delivery office': 'document_number',
            'transportation office': 'document_number',
            'fleet office': 'document_number',
            'maintenance office': 'document_number',
            'repair office': 'document_number',
            'service office': 'document_number',
            'quality office': 'document_number',
            'inspection office': 'document_number',
            'testing office': 'document_number',
            'certification office': 'document_number',
            'compliance office': 'document_number',
            'regulatory office': 'document_number',
            'legal office': 'document_number',
            'finance office': 'document_number',
            'accounting office': 'document_number',
            'audit office': 'document_number',
            'tax office': 'document_number',
            'insurance office': 'document_number',
            'risk office': 'document_number',
            'security office': 'document_number',
            'safety office': 'document_number',
            'health office': 'document_number',
            'environment office': 'document_number',
            'human resources office': 'document_number',
            'personnel office': 'document_number',
            'training office': 'document_number',
            'development office': 'document_number',
            'research office': 'document_number',
            'innovation office': 'document_number',
            'technology office': 'document_number',
            'information office': 'document_number',
            'communication office': 'document_number',
            'public relations office': 'document_number',
            'media office': 'document_number',
            'press office': 'document_number',
            'publicity office': 'document_number',
            'advertising office': 'document_number',
            'promotion office': 'document_number',
            'event office': 'document_number',
            'conference office': 'document_number',
            'meeting office': 'document_number',
            'seminar office': 'document_number',
            'workshop office': 'document_number',
            'training office': 'document_number',
            'education office': 'document_number',
            'learning office': 'document_number',
            'study office': 'document_number',
            'examination office': 'document_number',
            'assessment office': 'document_number',
            'evaluation office': 'document_number',
            'review office': 'document_number',
            'analysis office': 'document_number',
            'investigation office': 'document_number',
            'inquiry office': 'document_number',
            'survey office': 'document_number',
            'monitoring office': 'document_number',
            'tracking office': 'document_number',
            'reporting office': 'document_number',
            'documentation office': 'document_number',
            'record office': 'document_number',
            'archive office': 'document_number',
            'library office': 'document_number',
            'database office': 'document_number',
            'registry office': 'document_number',
            'registration office': 'document_number',
            'licensing office': 'document_number',
            'permit office': 'document_number',
            'authorization office': 'document_number',
            'approval office': 'document_number',
            'clearance office': 'document_number',
            'customs office': 'document_number',
            'immigration office': 'document_number',
            'visa office': 'document_number',
            'passport office': 'document_number',
            'consular office': 'document_number',
            'embassy office': 'document_number',
            'diplomatic office': 'document_number',
            'foreign office': 'document_number',
            'international office': 'document_number',
            'trade office': 'document_number',
            'commercial office': 'document_number',
            'business office': 'document_number',
            'economic office': 'document_number',
            'financial office': 'document_number',
            'investment office': 'document_number',
            'development office': 'document_number',
            'planning office': 'document_number',
            'policy office': 'document_number',
            'strategy office': 'document_number',
            'management office': 'document_number',
            'administration office': 'document_number',
            'executive office': 'document_number',
            'director office': 'document_number',
            'manager office': 'document_number',
            'supervisor office': 'document_number',
            'coordinator office': 'document_number',
            'specialist office': 'document_number',
            'expert office': 'document_number',
            'consultant office': 'document_number',
            'advisor office': 'document_number',
            'counselor office': 'document_number',
            'representative office': 'document_number',
            'agent office': 'document_number',
            'broker office': 'document_number',
            'dealer office': 'document_number',
            'trader office': 'document_number',
            'merchant office': 'document_number',
            'vendor office': 'document_number',
            'supplier office': 'document_number',
            'provider office': 'document_number',
            'contractor office': 'document_number',
            'subcontractor office': 'document_number',
            'partner office': 'document_number',
            'associate office': 'document_number',
            'affiliate office': 'document_number',
            'subsidiary office': 'document_number',
            'client office': 'document_number',
            'customer office': 'document_number',
            'buyer office': 'document_number',
            'purchaser office': 'document_number',
            'seller office': 'document_number',
            'vendor office': 'document_number',
            'supplier office': 'document_number',
            'provider office': 'document_number',
            'distributor office': 'document_number',
            'retailer office': 'document_number',
            'wholesaler office': 'document_number',
            'manufacturer office': 'document_number',
            'producer office': 'document_number',
            'creator office': 'document_number',
            'developer office': 'document_number',
            'designer office': 'document_number',
            'architect office': 'document_number',
            'engineer office': 'document_number',
            'technician office': 'document_number',
            'operator office': 'document_number',
            'worker office': 'document_number',
            'employee office': 'document_number',
            'staff office': 'document_number',
            'personnel office': 'document_number',
            'crew office': 'document_number',
            'team office': 'document_number',
            'group office': 'document_number',
            'unit office': 'document_number',
            'section office': 'document_number',
            'division office': 'document_number',
            'department office': 'document_number',
            'ministry office': 'document_number',
            'bureau office': 'document_number',
            'agency office': 'document_number',
            'authority office': 'document_number',
            'government office': 'document_number',
            'administration office': 'document_number',
            'legislature office': 'document_number',
            'chamber office': 'document_number',
            'house office': 'document_number',
            'senate office': 'document_number',
            'parliament office': 'document_number',
            'congress office': 'document_number',
            'assembly office': 'document_number',
            'council office': 'document_number',
            'commission office': 'document_number',
            'committee office': 'document_number',
            'panel office': 'document_number',
            'court office': 'document_number',
            'tribunal office': 'document_number',
            'inquiry office': 'document_number',
            'investigation office': 'document_number',
            'audit office': 'document_number',
            'inspection office': 'document_number',
            'examination office': 'document_number',
            'assessment office': 'document_number',
            'evaluation office': 'document_number',
            'review office': 'document_number',
            'advisory office': 'document_number',
            'executive office': 'document_number',
            'management office': 'document_number',
            'control office': 'document_number',
            'monitoring office': 'document_number',
            'tracking office': 'document_number',
            'scheduling office': 'document_number',
            'planning office': 'document_number',
            'coordination office': 'document_number',
            'communication office': 'document_number',
            'announcement office': 'document_number',
            'display office': 'document_number',
            'information office': 'document_number',
            'notice office': 'document_number',
            'message office': 'document_number',
            'bulletin office': 'document_number',
            'advisory office': 'document_number',
            'caution office': 'document_number',
            'warning office': 'document_number',
            'alert office': 'document_number',
            'reminder office': 'document_number',
            'memo office': 'document_number',
            'note office': 'document_number',
            'observation office': 'document_number',
            'remark office': 'document_number',
            'comment office': 'document_number',
            'feedback office': 'document_number',
            'reply office': 'document_number',
            'response office': 'document_number',
            'answer office': 'document_number',
            'question office': 'document_number',
            'query office': 'document_number',
            'inquiry office': 'document_number',
            'request office': 'document_number',
            'command office': 'document_number',
            'order office': 'document_number',
            'direction office': 'document_number',
            'instruction office': 'document_number',
            'guidance office': 'document_number',
            'advice office': 'document_number',
            'recommendation office': 'document_number',
            'suggestion office': 'document_number',
            'proposal office': 'document_number',
            'motion office': 'document_number',
            'resolution office': 'document_number',
            'decision office': 'document_number',
            'discussion office': 'document_number',
            'conference office': 'document_number',
            'meeting office': 'document_number',
            'minute office': 'document_number',
            'entry office': 'document_number',
            'diary office': 'document_number',
            'logbook office': 'document_number',
            'log office': 'document_number',
            'record office': 'document_number',
            'register office': 'document_number',
            'index office': 'document_number',
            'directory office': 'document_number',
            'catalog office': 'document_number',
            'inventory office': 'document_number',
            'list office': 'document_number',
            'schedule office': 'document_number',
            'exhibit office': 'document_number',
            'enclosure office': 'document_number',
            'attachment office': 'document_number',
            'appendix office': 'document_number',
            'supplement office': 'document_number',
            'addendum office': 'document_number',
            'amendment office': 'document_number',
            'termination office': 'document_number',
            'cancellation office': 'document_number',
            'rejection office': 'document_number',
            'acceptance office': 'document_number',
            'confirmation office': 'document_number',
            'recap office': 'document_number',
            'note office': 'document_number',
            'party office': 'document_number',
            'contract office': 'document_number',
            'agreement office': 'document_number',
            'consent office': 'document_number',
            'permission office': 'document_number',
            'authorization office': 'document_number',
            'approval office': 'document_number',
            'endorsement office': 'document_number',
            'initial office': 'document_number',
            'signature office': 'document_number',
            'seal office': 'document_number',
            'stamp office': 'document_number',
            'sticker office': 'document_number',
            'tag office': 'document_number',
            'label office': 'document_number',
            'signage office': 'document_number',
            'banner office': 'document_number',
            'poster office': 'document_number',
            'flyer office': 'document_number',
            'leaflet office': 'document_number',
            'pamphlet office': 'document_number',
            'brochure office': 'document_number',
            'publication office': 'document_number',
            'journal office': 'document_number',
            'magazine office': 'document_number',
            'newsletter office': 'document_number',
            'bulletin office': 'document_number',
            'announcement office': 'document_number',
            'notice office': 'document_number',
            'memorandum office': 'document_number',
            'letter office': 'document_number',
            'directive office': 'document_number',
            'instruction office': 'document_number',
            'information office': 'document_number',
            'notification office': 'document_number',
            'invitation office': 'document_number',
            'congratulation office': 'document_number',
            'you office': 'document_number',
            'appreciation office': 'document_number',
            'commendation office': 'document_number',
            'recognition office': 'document_number',
            'award office': 'document_number',
            'achievement office': 'document_number',
            'participation office': 'document_number',
            'attendance office': 'document_number',
            'completion office': 'document_number',
            'clearance office': 'document_number',
            'objection office': 'document_number',
            'character office': 'document_number',
            'conduct office': 'document_number',
            'service office': 'document_number',
            'experience office': 'document_number',
            'reference office': 'document_number',
            'recommendation office': 'document_number',
            'relieving office': 'document_number',
            'joining office': 'document_number',
            'off office': 'document_number',
            'on office': 'document_number',
            'change office': 'document_number',
            'repatriation office': 'document_number',
            'leave office': 'document_number',
            'leave office': 'document_number',
            'record office': 'document_number',
            'agreement office': 'document_number',
            'agreement office': 'document_number',
            'contract office': 'document_number',
            'record office': 'document_number',
            'book office': 'document_number',
            'book office': 'document_number',
            'passport office': 'document_number',
            'visa office': 'document_number',
            'certificate office': 'document_number',
            'certificate office': 'document_number',
            'certificate office': 'document_number',
            'record office': 'document_number',
            'report office': 'document_number',
            'permit office': 'document_number',
            'permit office': 'document_number',
            'permit office': 'document_number',
            'permit office': 'document_number',
            'permit office': 'document_number',
            'watch office': 'document_number',
            'meeting office': 'document_number',
            'report office': 'document_number',
            'record office': 'document_number',
            'certificate office': 'document_number',
            'certificate office': 'document_number',
            'certificate office': 'document_number',
            'certificate office': 'document_number',
            'free office': 'document_number',
            'report office': 'document_number',
            'cleaning office': 'document_number',
            # Fuel/Chemical Properties mappings
             'dist ibp': 'dist_ibp',
             'dist 10': 'dist_10',
             'dist 50': 'dist_50',
             'dist 90': 'dist_90',
             'dist fbp': 'dist_fbp',
             'dist residue': 'dist_residue',
             'smoke point': 'smoke_point',
             'cloud point': 'cloud_point',
             'cfpp': 'cfpp',
             'carbon residue': 'carbon_residue',
             'viscosity 40': 'viscosity_40',
             'viscosity 100': 'viscosity_100',
             'viscosity index': 'viscosity_index',
             'api gravity': 'api_gravity',
             'specific gravity': 'specific_gravity',
             'cetane number': 'octane_number',
             'calorific value': 'calorific_value',
             'lubricity': 'lubricity',
             'aromatics': 'aromatics',
             'olefins': 'olefins',
             'oxygenates': 'oxygenates',
             'nitrogen': 'nitrogen',
             'nickel': 'nickel',
             'vanadium': 'vanadium',
             'sodium': 'sodium',
             'sediment': 'sediment'
        }
        
        return key_mappings.get(key, key.replace(' ', '_'))

    def _generate_fallback_value(self, placeholder_key):
        """Generate a fallback value for unknown placeholder keys."""
        key = placeholder_key.lower()
        
        # Generate appropriate fallback based on key patterns
        if 'date' in key or 'time' in key:
            return datetime.now().strftime('%Y-%m-%d')
        elif 'number' in key or 'id' in key:
            return f"REF-{random.randint(100000, 999999)}"
        elif 'name' in key:
            return random.choice(self.data_pools['name'])
        elif 'company' in key:
            return random.choice(self.data_pools['company_name'])
        elif 'port' in key:
            return random.choice(self.data_pools['port_name'])
        elif 'country' in key:
            return random.choice(self.data_pools['country'])
        elif 'email' in key:
            return random.choice(self.data_pools['email'])
        elif 'phone' in key:
            return random.choice(self.data_pools['phone'])
        elif 'address' in key:
            return random.choice(self.data_pools['address'])
        elif 'quantity' in key or 'amount' in key:
            return random.choice(self.data_pools['quantity'])
        else:
            return f"[{placeholder_key}]"