from docx import Document
from docx.shared import Inches

def create_sample_document():
    """Create a sample Word document with placeholders for testing"""
    doc = Document()
    
    # Add title
    title = doc.add_heading('Vessel Information Report', 0)
    title.alignment = 1  # Center alignment
    
    # Add vessel basic information
    doc.add_heading('Basic Vessel Information', level=1)
    
    p1 = doc.add_paragraph()
    p1.add_run('Vessel Name: ').bold = True
    p1.add_run('{{vessel_name}}')
    
    p2 = doc.add_paragraph()
    p2.add_run('IMO Number: ').bold = True
    p2.add_run('{{imo}}')
    
    p3 = doc.add_paragraph()
    p3.add_run('Vessel Type: ').bold = True
    p3.add_run('{{vessel_type}}')
    
    p4 = doc.add_paragraph()
    p4.add_run('Flag State: ').bold = True
    p4.add_run('{{flag}}')
    
    # Add technical specifications
    doc.add_heading('Technical Specifications', level=1)
    
    p5 = doc.add_paragraph()
    p5.add_run('Length Overall: ').bold = True
    p5.add_run('{{length}}')
    
    p6 = doc.add_paragraph()
    p6.add_run('Beam: ').bold = True
    p6.add_run('{{width}}')
    
    p7 = doc.add_paragraph()
    p7.add_run('Deadweight Tonnage: ').bold = True
    p7.add_run('{{tonnage}}')
    
    p8 = doc.add_paragraph()
    p8.add_run('Maximum Speed: ').bold = True
    p8.add_run('{{speed}}')
    
    # Add crew information
    doc.add_heading('Crew Information', level=1)
    
    p9 = doc.add_paragraph()
    p9.add_run('Captain/Master: ').bold = True
    p9.add_run('{{captain}}')
    
    p10 = doc.add_paragraph()
    p10.add_run('Crew Size: ').bold = True
    p10.add_run('{{crew}}')
    
    # Add company information
    doc.add_heading('Company Information', level=1)
    
    p11 = doc.add_paragraph()
    p11.add_run('Ship Owner: ').bold = True
    p11.add_run('{{company}}')
    
    p12 = doc.add_paragraph()
    p12.add_run('Contact Email: ').bold = True
    p12.add_run('{{email}}')
    
    p13 = doc.add_paragraph()
    p13.add_run('Contact Phone: ').bold = True
    p13.add_run('{{phone}}')
    
    p14 = doc.add_paragraph()
    p14.add_run('Company Address: ').bold = True
    p14.add_run('{{address}}')
    
    # Add operational information
    doc.add_heading('Operational Information', level=1)
    
    p15 = doc.add_paragraph()
    p15.add_run('Current Port: ').bold = True
    p15.add_run('{{port}}')
    
    p16 = doc.add_paragraph()
    p16.add_run('Year Built: ').bold = True
    p16.add_run('{{year}}')
    
    p17 = doc.add_paragraph()
    p17.add_run('Report Date: ').bold = True
    p17.add_run('{{date}}')
    
    p18 = doc.add_paragraph()
    p18.add_run('Report Time: ').bold = True
    p18.add_run('{{time}}')
    
    # Add a table with placeholders
    doc.add_heading('Summary Table', level=1)
    
    table = doc.add_table(rows=1, cols=2)
    table.style = 'Table Grid'
    hdr_cells = table.rows[0].cells
    hdr_cells[0].text = 'Property'
    hdr_cells[1].text = 'Value'
    
    # Add table rows with placeholders
    properties = [
        ('Vessel Name', '{{vessel_name}}'),
        ('IMO Number', '{{imo}}'),
        ('Vessel Type', '{{vessel_type}}'),
        ('Flag State', '{{flag}}'),
        ('Captain', '{{captain}}'),
        ('Current Port', '{{port}}')
    ]
    
    for prop, value in properties:
        row_cells = table.add_row().cells
        row_cells[0].text = prop
        row_cells[1].text = value
    
    # Add footer
    doc.add_page_break()
    footer_para = doc.add_paragraph()
    footer_para.add_run('This document was automatically generated by the Document Auto-Fill System.').italic = True
    footer_para.alignment = 1  # Center alignment
    
    # Save the document
    doc.save('sample_vessel_report.docx')
    print("Sample document created: sample_vessel_report.docx")

if __name__ == "__main__":
    create_sample_document()