name: autofill-service

services:
- name: api
  source_dir: /
  github:
    repo: jeanclaudder2024/pythonfillproject
    branch: main
  run_command: python working_fastapi.py
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  
  envs:
  - key: PORT
    value: "8000"
  - key: PYTHON_VERSION
    value: "3.11"
    
  health_check:
    http_path: /health
    
  http_port: 8000
